version: "3.9"

services:
  mongo:
    image: mirror.gcr.io/library/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27020:27017"
    networks:
      - mongo-network
    volumes:
      - mongo_data:/data/db

  calculadora:
    build:
      context: ./backend
    image: calculadora-fast-api
    ports:
      - "8089:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - mongo-network
    environment:
      - MONGO_URL=mongodb://admin_user:web3@mongo:27017/

  frontend:
    build:
      context: ./frontend
    image: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8089
    depends_on:
      - calculadora
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo_data:

